services:
    mcro_sylius_nmi_plugin.action.direct_post:
        class: MCRO\SyliusNMIPlugin\Payum\Action\DirectPostAction
        public: true
        arguments:
            - "@sylius.http_client"
        tags:
            - { name: payum.action, factory: nmi_payment, alias: payum.action.direct_post }

    mcro_sylius_nmi_plugin.action.status:
        class: MCRO\SyliusNMIPlugin\Payum\Action\StatusAction
        public: true
        tags:
            - { name: payum.action, factory: nmi_payment, alias: payum.action.status }

    mcro_sylius_nmi_plugin.action.obtain_token:
        class: MCRO\SyliusNMIPlugin\Payum\Action\ObtainTokenAction
        public: true
        arguments:
            - "MCROSyliusNMIPlugin/payment.html.twig"
        tags:
            - { name: payum.action, factory: nmi_payment, alias: payum.action.obtain_token }

    mcro_sylius_nmi_plugin.action.capture:
        class: MCRO\SyliusNMIPlugin\Payum\Action\CaptureAction
        public: true
        tags:
            - { name: payum.action, factory: nmi_payment, alias: payum.action.capture }

    mcro_sylius_nmi_plugin.action.execute_same_request_with_payment_details:
        class: MCRO\SyliusNMIPlugin\Payum\Action\ExecuteSameRequestWithPaymentDetailsAction
        public: true
        tags:
            - { name: payum.action, factory: nmi_payment, alias: payum.action.execute_same_request_with_payment_details }
